title: Post dump
email: traxdater12@gmail.com
description: Stuff I find interesting
baseurl: ''
url: 'rajcevic.org'
twitter_username: lurajcevi
github_username: epson121
markdown: kramdown
theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 5
paginate_path: /page:num/
search_full_content: true
