locale: "en-us"
title: "Post dump"
description: "Stuff I find interesting"
email: "traxdater12@gmail.com"
date_format: "%d-%m-%Y"

# read time
# read_time: true
# words_per_minute: 200

# google fonts
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# pagination
paginate: 5
paginate_path: /page:num/

# taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# disqus integration
disqus:
  shortname: lurajcevi

# google-analytics
google_analytics: UA-52335198-1


baseurl: ''
url: 'http://rajcevic.org'
twitter_username: lurajcevi
github_username: epson121
markdown: kramdown
theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed
  - jekyll-paginate
search_full_content: true
